-- PostgreSQL 데이터베이스 초기화 스크립트
-- 이 스크립트는 PostgreSQL superuser 권한으로 실행해야 합니다.

-- M14 Fab Database 생성
CREATE DATABASE m14db;

-- M15 Fab Database 생성  
CREATE DATABASE m15db;

-- M16 Fab Database 생성
CREATE DATABASE m16db;

-- M14 사용자 생성 및 권한 부여
CREATE USER m14_user WITH PASSWORD 'm14_password';
GRANT ALL PRIVILEGES ON DATABASE m14db TO m14_user;
GRANT CONNECT ON DATABASE m14db TO m14_user;

-- M15 사용자 생성 및 권한 부여
CREATE USER m15_user WITH PASSWORD 'm15_password';
GRANT ALL PRIVILEGES ON DATABASE m15db TO m15_user;
GRANT CONNECT ON DATABASE m15db TO m15_user;

-- M16 사용자 생성 및 권한 부여
CREATE USER m16_user WITH PASSWORD 'm16_password';
GRANT ALL PRIVILEGES ON DATABASE m16db TO m16_user;
GRANT CONNECT ON DATABASE m16db TO m16_user;

-- 각 데이터베이스에 대한 스키마 권한 설정
\c m14db;
GRANT ALL ON SCHEMA public TO m14_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO m14_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO m14_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO m14_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO m14_user;

\c m15db;
GRANT ALL ON SCHEMA public TO m15_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO m15_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO m15_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO m15_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO m15_user;

\c m16db;
GRANT ALL ON SCHEMA public TO m16_user;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO m16_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO m16_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO m16_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO m16_user; 