server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-mes-backend
  
  profiles:
    active: local
  
  # Environment Variables Configuration
  config:
    import: optional:file:.env.local
  
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: SNAKE_CASE
  
  security:
    jwt:
      secret: ai-mes-jwt-secret-key-for-development-only-change-in-production
      expiration: 86400000 # 24 hours

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.ai.mes.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

# AI Service Configuration
ai-service:
  base-url: http://localhost:8000
  timeout: 30000

# Logging Configuration
logging:
  level:
    com.ai.mes: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

---
# Local Development Profile
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    # M14 Fab Database
    m14:
      jdbc-url: ${M14_DB_URL}
      username: ${M14_DB_USERNAME}
      password: ${M14_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # M15 Fab Database  
    m15:
      jdbc-url: ${M15_DB_URL}
      username: ${M15_DB_USERNAME}
      password: ${M15_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # M16 Fab Database
    m16:
      jdbc-url: ${M16_DB_URL}
      username: ${M16_DB_USERNAME}
      password: ${M16_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # Next Login Database
    next:
      jdbc-url: ${NEXT_DB_URL}
      username: ${NEXT_DB_USERNAME}
      password: ${NEXT_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

---
# Production Profile
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    # M14 Fab Database
    m14:
      jdbc-url: ${M14_DB_URL}
      username: ${M14_DB_USERNAME}
      password: ${M14_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # M15 Fab Database  
    m15:
      jdbc-url: ${M15_DB_URL}
      username: ${M15_DB_USERNAME}
      password: ${M15_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # M16 Fab Database
    m16:
      jdbc-url: ${M16_DB_URL}
      username: ${M16_DB_USERNAME}
      password: ${M16_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      
    # Next Login Database
    next:
      jdbc-url: ${NEXT_DB_URL}
      username: ${NEXT_DB_USERNAME}
      password: ${NEXT_DB_PASSWORD}
      driver-class-name: org.postgresql.Driver
      # PostgreSQL 연결 풀 설정
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000